# Generated by Django 5.2.13 on 2026-04-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("great", "Great"),
                            ("good", "Good"),
                            ("okay", "Okay"),
                            ("low", "Low"),
                            ("bad", "Bad"),
                        ],
                        max_length=20,
                    ),
                ),
                ("energy_level", models.PositiveSmallIntegerField()),
                ("focus_score", models.PositiveSmallIntegerField()),
                ("wins", models.TextField(blank=True)),
                ("problems", models.TextField(blank=True)),
                ("lessons", models.TextField(blank=True)),
                ("tomorrow_plan", models.TextField(blank=True)),
                ("overall_score", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
