# Generated by Django 5.2.13 on 2026-04-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyReflection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start_date", models.DateField(unique=True)),
                ("wins", models.TextField(blank=True)),
                ("problems", models.TextField(blank=True)),
                ("lessons", models.TextField(blank=True)),
                ("next_week_focus", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-week_start_date"],
            },
        ),
    ]
